### ISSUE TITLE
Does the scale component of the tile transform apply to tile's geometric error?

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/3d-tiles#462] opened 2021-04-06 18:39 UTC
I encountered this issue https://github.com/CesiumGS/cesium/issues/5330 on cesium-unreal side since the plugin doesn't apply the scale component to the geometric error according to the [spec](https://github.com/CesiumGS/3d-tiles/tree/master/specification#tile-transforms). However, [CesiumJS already did](https://github.com/CesiumGS/cesium/blob/ab07bcb130d99baaae08ce5e4346ae79899136e0/Source/Scene/Cesium3DTile.js#L1474). Should we update the specs on that? or are there underlying problems with it

**Comment by lilleyse** [comment] 2021-04-06 18:51
Duplicate of https://github.com/CesiumGS/3d-tiles/issues/367

**Closed by lilleyse** 2021-04-06 18:51 UTC
